### ISSUE TITLE
HTML comments containing PHP

### ISSUE THREAD

**Issue by egst** [tree-sitter/tree-sitter-php#119]
HTML comments are not highlighted when they contain PHP code in `<?php ... ?>` tags.

This works well:

```php
<!--
<div>
</div>
-->
```

However, this doesn't:

```php
<!--
<div>
    <?php echo 'foo' ?>
</div>
-->
```

**Comment by mikehaertl** [comment]
It seems this is not just a problem with comments but with any PHP that is nested inside HTML tags:
![ts_html_in_php](https://user-images.githubusercontent.com/675062/150750164-48d29b28-ad1f-420c-84ad-b6256ed47e4b.png)
Notice the `<div>` in line 4 which is not highlighted correctly. There are also errors in the parse tree on the left.

I wonder if this is because with PHP in many cases you can't say that HTML is embedded in PHP but rather the opposite: Even if its a `.php` file it looks more like a HTML file with a couple of embedded PHP snippets. In that case I assume that the injected HTML parser sees two independent blocks: lines 1-2 and lines 4-7. The second block starts with a standalone closing tag which results in an error.

It's probably a limitation of how treesitter works with injections. Ideally we could define that for PHP files it's not only HTML injected into PHP but also PHP injected into HTML.

**Comment by egst** [comment]
@mikehaertl, yes, I use nvim and I'm also seeing the problem that you describe, but it's not consistent on all color schemes in my case.

**Comment by maxbrunsfeld** [comment]
Can you reopen this on the nvim-treesitter repository? This isn't a problem with the PHP parser.

**Comment by maxbrunsfeld** [comment]
Just for further context, GitHub.com is using this same parser for highlighting the code below, which mixes PHP and HTML and it works fine:

```php
<?php echo 'top-level PHP tag' ?>

<div
  class="<?php echo 'inside-attribute' ?>"
>
  
</div>

<!--
<div>
  <?php echo 'inside comment' ?>
</div>
-->
```

The problem that you're seeing is something specific to Neovim.
