### ISSUE TITLE
JS highliting

### ISSUE THREAD

**Issue by caasi-dev** [tree-sitter/tree-sitter-php#120]
Hello,
It appears that Javasscript code is not highlighting correctly?
![image](https://user-images.githubusercontent.com/60949037/151069998-c7a740a0-65ca-454e-a4ce-fece27a6334d.png)

**info**
NVIM v0.7.0-dev+923-gecec95712
Build type: Release

**Comment by mikehaertl** [comment]
IMO this is related to #119. The problem is that the parser only ever "sees" the incomplete HTML snippets between PHP tags. Like in your case for example: 

* `<script src="`: parsed correctly as partial HTML tag
* `/assets/js/custom/d3.js"</script>`: can not be parsed as valid HTML

To verify: If you remove the lines 1-4 everything should be fine again.

From what I found there's no fix with nvim-treesitter yet. It could be fixed with the `@combined` feature which according to [this comment](https://github.com/nvim-treesitter/nvim-treesitter/issues/2212#issuecomment-1010028520) still has issues.

**Comment by caasi-dev** [comment]
yes, you are absolutely right here, thank you, will monitor issue you mentioned. Thank you, closing this as not really problem with this package.
