### ISSUE TITLE
Support any chars PHP accept for names and labels

### ISSUE THREAD

**Issue by cfroystad** [tree-sitter/tree-sitter-php#142]
Currently, we only support (extended?) ASCII for names and labels in accordance with the [PHP documentation](https://www.php.net/manual/en/language.variables.basics.php). However, this is not consistent with how PHP actually works.

This entails two tings:

1. Investigate what's the true definition of a legal name/label in PHP (a PR to update the official documentation will probably be appreciated)
2. Modify the method `is_valid_name_char` in [src/scanner.cc](https://github.com/tree-sitter/tree-sitter-php/blob/master/src/scanner.cc#L114) to account for the identified rules
3. Modify the `name` rule in [grammar.js](https://github.com/tree-sitter/tree-sitter-php/blob/master/grammar.js#L1376) to account for the same rules

**Comment by rever1and** [comment]
Should it be?

```
[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]
```

I just encountered with a something like

```
$\xf9\xdf=strlen("aaa");
```

which will be parsed as `(function_call_expression function: (variable_name))`.

**Comment by calebdw** [comment]
@cfroystad, @amaanq,

I've been digging into this and here are my findings, the BLUF is that I don't think we need to support *every* char that PHP accepts as a valid identifier.

### Valid PHP Labels

The PHP scanner declares that a valid `LABEL` is `[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*` which is consistent with what is currently listed in the docs:
- https://github.com/php/php-src/blob/b06fedb41d560f756dfb5d964b0d36a224e44dc7/Zend/zend_language_scanner.l#L1365
- https://www.php.net/manual/en/language.variables.basics.php
- https://github.com/php/php-src/blob/b06fedb41d560f756dfb5d964b0d36a224e44dc7/Zend/zend_language_scanner.l#L2345-L2347

### Discrepancies

From what I've been reading, PHP accepting variable names like the following (taken from #171):
```php
<?php
$漢字;
```
as valid is more of a bug rather than a feature. From my understanding, this is occurring because PHP isn't handling UTF-8 properly and is matching the individual UTF-8 bytes against the range `\x80-\xff`.

- https://stackoverflow.com/questions/5358824/unicode-identifiers-function-names-for-non-localization-purposes-advisable
- https://stackoverflow.com/questions/3417180/exotic-names-for-methods-constants-variables-and-fields-bug-or-feature


### Path Forward

It would be easy enough to update the regex to allow any character in the UTF-8 range:
```diff
-      name: _ => /[_a-zA-Z\u00A1-\u00ff][_a-zA-Z\u00A1-\u00ff\d]*/,
+      name: _ => /[_a-zA-Z\u0080-\uffff][_a-zA-Z\u0080-\uffff\d]*/,
```

However, doing so greatly increases the size of the parser and the large range is not efficient:

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/25539575-c30b-49b2-90b6-677d89f6e2a4)

Given that: a) any character > `\xff` is technically illegal in PHP, and b) the parser large growth by trying to be all-inclusive, I'd say that we should stick to the legal definition.

We currently use a different regex, so if anything we should just update it to be consistent:
```diff
-      name: _ => /[_a-zA-Z\u00A1-\u00ff][_a-zA-Z\u00A1-\u00ff\d]*/,
+      name: _ => /[_a-zA-Z\u0080-\u00ff][_a-zA-Z\u0080-\u00ff\d]*/,
```

**Comment by amaanq** [comment]
Hey that's an interesting side effect/bug potentially. I tried random values from 0x80 to 0xa0, it only reduces after 0xa0 (a1) which is interesting. I'll dig more in core to see why that is and if it is potentially a bug

**Comment by amaanq** [comment]
Found it, using 0xA0 is tricky because it's also used as whitespace - which is valid..anywhere due to it being in the extras.

Sidestepping this like so keeps the state count low:
 `name: _ => /[_a-zA-Z\u009f\u00A1-\u00ff][_a-zA-Z\u009f\u00A1-\u00ff\d]*/,`
 
 @calebdw 0x85 is also considered whitespace, but using it doesn't blow up the state count, because it wasn't explicitly added in the extras rule. We had a talk about this a while ago about whether or not to add more whitespace character here: https://github.com/tree-sitter/tree-sitter/pull/2428, and in the end we opted to add VT and FF only 

 Removing the explicit mention of `\u00A0` fixes this blow up. So, what we can do is one of two things.
 
 Sidestep A0 entirely in the name rule and use ranges below and above that or
 Remove A0 from the extras
 
 Up to you

**Comment by calebdw** [comment]
Ah, very interesting. But I guess this raises several questions:

- does `\u00a0` need to be in the extras and what could be some side-effects of removing it?
- do you think we should support the full utf-8 range `\uffff` or just stop at `\u00ff`?

**Comment by amaanq** [comment]
it's technically considered a whitespace character

as for the range stuff, I think it'd be best to stick to what's official - if there's a discrepancy in the docs and reality because of php not handling utf-8 properly then I would go with `\uffff` for a better UX for downstream in these rare cases. I don't think performance will be hurt all that much, since ranges are just a simple cmp operation when compiled down (if it's not half-open like it could be for the A0 case)

Note that 200B, 2060, and FEFF are used for whitespace as well, so I'd sidestep around these too
