### ISSUE TITLE
Parse more keywords and language constructs

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-php#144]
For use in semgrep, it would be nice if tree-sitter-php parsed more keywords and language constructs. Specifically:

* $this
* isset()
* empty()
* eval()
* exit() / die()
* assert()
* __halt_compiler()
* maybe `__CLASS__`, `__DIR__`, `__FILE__`, `__FUNCTION__`, `__LINE__`, `__METHOD__`, `__NAMESPACE__`, `__TRAIT__`?

`$this` is of course not a real variable, but refers to the current object. The other ones are language constructs, not real functions.

These do not currently trigger a parse error, but are parsed as variable or function call, when that is not technically correct.

**Comment by maxbrunsfeld** [comment]
The downside of including these in the grammar is that they'll increase the size of the parser, and with the current grammar, these can already be identified at a different layer of abstraction.

If we do add them to these builtins to the grammar, I think they should be done so as one single new token, for efficiency:

```js
builtin_function_name: $ => token(choice(
  'die',
  'exit',
  'isset',
  'empty',
  // ...
)),

function_call_expression: $ => seq(
  field('function', choice(
    $.builtin_function_name,
    $.qualified_name,
    // ...
  )),
  field('arguments', $.arguments),
)
```

That will reduce the impact on the parser's code size.

On a related note, I think `unset` is currently treated as its own kind of statement, which is unnecessarily specific (and costly, in terms of code size). It should really be handled the same way as these other built-in functions: either parsed as a simple `name`, or if we choose to add it, as a `builtin_function_name`.

**Comment by cfroystad** [comment]
After giving this some more thought, I fear my initial enthusiasm was a bit premeditated.

Currently, we have quite a few paths in the parser where we take a relaxed approach to correctness (to keep parser since small) and primarily concern ourselves with syntactic correctness while (mostly?) leaving semantic correctness to another layer of abstraction.

To me, this feels like a cross road where if we implement this, we should also implement other semantic checking (e.g. not allowing functions with names equal to the language constructs) - and I don't think that's in scope of the grammar. However, I'm still learning, so please correct me if I'm wrong 🙂 

As far as I can see, the suggestion in the earlier comment would still require Yoann's suggestion of having a `fix_funcall` or `fix_id` in Parse_php_tree_sitter.ml. Thus, this change would probably at best only have a small positive impact on Semgrep since further processing will be required anyway. Is that a fair assessment/understanding? If so, I guess the easiest fix would be to remove the `__bultin_` prefix from pfff since PHP code trying to declare a language construct as a function will fail compilation - at least in my tests.

I'm inclined to support removing `unset` as it's own statement and keep the parser as simple as possible, leaving semantics to users of the grammar. At least I'll focus on completing the support for current PHP syntax before thinking more about this myself.
