### ISSUE TITLE
single escaped quotes recognized as string

### ISSUE THREAD

**Issue by vpxyz** [tree-sitter/tree-sitter-php#173]
This simple test, taken from emacs php-mode:
```
<?php

/**
 * GitHub Issue:    https://github.com/emacs-php/php-mode/issues/174
 *
 * Test highlighting of string literals containing escaped quotes
 */

'escaped single \' quotation mark';
"escaped double \" quotation mark";
```

produce this syntax tree:

```
(program (php_tag) (comment)
 (expression_statement
  (string ' (string_value) ')
  ;)
 (expression_statement
  (encapsed_string " (string_value) (escape_sequence) (string_value) ")
  ;))

```
Tested with tree-sitter 0.20.7 and the latest tree-sitter-php source tree.
Thank you

**Comment by calebdw** [comment]
What is the problem here? `\'` is not an escape sequence---everything looks fine to me

**Comment by vpxyz** [comment]
From https://www.php.net/manual/en/language.types.string.php, "Single quoted" paragraph:

> To specify a literal single quote, escape it with a backslash (\). To specify a literal backslash, double it (\\). All other instances of backslash will be treated as a literal backslash: this means that the other escape sequences you might be used to, such as \r or \n, will be output literally as specified rather than having any special meaning. 

I'm probably wrong, but I expected this type of sequence to be denoted by its own specific node as well. Not necessarily the same one used for `\"` . Otherwise only with a regular expression is it possible to highlight the syntax.

Thanks

**Comment by calebdw** [comment]
Perhaps @cfroystad could weigh in here if I'm incorrect, but according to the docs there are no escape sequences in single quoted strings:

> Note: Unlike the [double-quoted](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.double) and [heredoc](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) syntaxes, [variables](https://www.php.net/manual/en/language.variables.php) and escape sequences for special characters will not be expanded when they occur in single quoted strings.

Anything inside the string is just a string---there's no need for the `\'` to have its own node in a single quoted string.

> Otherwise only with a regular expression is it possible to highlight the syntax.

The `\'` should **not** be highlighted differently than the rest of the string. Also, why are you trying to use regex highlighting when you have treesitter?

**Comment by vpxyz** [comment]
![image](https://github.com/tree-sitter/tree-sitter-php/assets/9392182/2b4c9f11-b348-4958-b41d-4b7c8858a548)
The interpreter treats them differently, which is why I wish I could highlight them differently.
In the emacs major mode I am writing I used regexes to highlight phpdoc syntax. The current implementation of "tree-siter-phpdoc" does not support, for example, psalm or phpstan tags.

**Comment by calebdw** [comment]
The phpdoc parser *does* support many psalm tags and it would be easy enough to add support for more phpstan tags:

https://github.com/claytonrcarter/tree-sitter-phpdoc/blob/915a527d5aafa81b31acf67fab31b0ac6b6319c0/grammar.js#L489-L515


Not sure what this has to do with highlighting phpdocs, but I still think this parser is correct in handling it as a string and don't see a need for a separate node.

**Comment by cfroystad** [comment]
Some points of reference:

- [PHPSpecification on single quoted string literals](https://phplang.org/spec/09-lexical-structure.html#single-quoted-string-literals) (keep in mind that this might be quite outdated/inconsistent at places, so this is not a perfect source)
- [PHP-parser tests related to constant string literals](https://github.com/nikic/PHP-Parser/blob/master/test/code/parser/scalar/constantString.test) and [PHP-parser pretty printer for the constantString literals](https://github.com/nikic/PHP-Parser/blob/1eeeb2d5252d6d8706c5a8d9d88b8d1e7ecf2109/lib/PhpParser/PrettyPrinter/Standard.php#L1049)

As you can see, they're not fully in agreement on how to idiomatically handle this case. I'd like to do an export of the interpreter AST using [php-ast](https://github.com/nikic/php-ast) but am a bit pressed for time atm (I'll still review PRs and merge them quite fast in the days to come).

Since we're operating on CST here, rather than AST, I'm leaning towards including escape sequence for ' and \, however I've not examined the impact this would have on the complexity of the implementation (just remembering that at the time of implementation the encapsed string stuff were at the very edge of my abilities, so I suppose simplifications can be made when revisiting now :laughing: )

**Comment by vpxyz** [comment]
Thanks to both of you. I really appreciate your hard work in tackling this complicated task.
I will try phpdoc again. Injecting phpdoc into emacs is a bit tricky, apart from the problem of unsupported tags (I hope to do a pr as soon as I find some time), compared to injecting html/javascript/css.
Thanks
