### ISSUE TITLE
why isn't php injected via the html parser

### ISSUE THREAD

**Issue by Hippo0o** [tree-sitter/tree-sitter-php#178]
PHP files are just html with php code blocks in it. 
So why does this parser work the other way around combining html around the php code blocks to inject html? Would'nt it make more sense if the html parser injected php?

I'm asking because i was investigating issues i have using neovim and files that mainly have html with some php code in it.

**Comment by calebdw** [comment]
PHP is a templating engine which can be used for any type of text file---the treesitter query injects html because that's the most common, but the node itself is called `text` in the grammar which is indicative of this. Additionally, it shouldn't be the html parser's responsibility to analyze `.php` files.

> I'm asking because i was investigating issues i have using neovim and files that mainly have html with some php code in it.

What issues were you having?

**Comment by Hippo0o** [comment]
@calebdw i wrote about it here https://github.com/nvim-treesitter/nvim-treesitter/pull/4653#issuecomment-1593091425

**Comment by Hippo0o** [comment]
so the problem primarly lies with the nvim-treesitter implementation of querying injections

**Comment by calebdw** [comment]
Hmm, I don't see any issues with the Neovim hightlighting?

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/b6f1b966-ca69-473a-8fd9-8b91cac09fdf)

> so the problem primarly lies with the neovim treesitter implementation of querying injections
Sounds like this issue can be closed then

**Comment by Hippo0o** [comment]
Thanks for giving me an answer.
