### ISSUE TITLE
[bug] tree-sitter-php 0.22.4 should not have tree-sitter 0.21 as dep

### ISSUE THREAD

**Issue by HerringtonDarkholme** [tree-sitter/tree-sitter-php#239]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Describe the bug

Bumping tree-sitter dependency to 0.21 is a breaking change. So the version number should also be bumped to 0.21.0+

https://github.com/ast-grep/ast-grep/actions/runs/8975845192/job/24651378412

Proposal
Release a new version of 0.22.5 to downgrade tree-sitter dep and then release a new version of 0.23.0 to bump the dep version.

### Steps To Reproduce/Bad Parse Tree

https://github.com/ast-grep/ast-grep/actions/runs/8975845192/job/24651378412

### Expected Behavior/Parse Tree

Not available

### Repro

```PHP
See reported link above
```

**Comment by amaanq** [comment]
I get the sentiment, but tree-sitter **does not** strictly follow Rust's guideline on semver, which deviates from the official semver spec with regards to *zerover*, in that we *may* introduce incompatible changes between patch versions, because we do not only provide a Rust crate binding, but as well as a pypi package, npm package, C binding, Go binding, Swift binding, etc. So until we're 1.0, we're not going to follow Rust's semver since it deviates.

**Comment by amaanq** [comment]
I'll try to be more mindful going forth though, e.g. we are going to introduce a tree-sitter-language crate to expose the Language ptr without needing `tree-sitter` as a dependency - I'll bump the minor version for every grammar for this of course

**Comment by HerringtonDarkholme** [comment]
thanks for the explanation!
