### ISSUE TITLE
Highlighting issue

### ISSUE THREAD

**Issue by MurdeRMelodY** [tree-sitter/tree-sitter-php#51]
I'm not sure how to word this but, Is there a way to parse a variable_name in a string? In an echo statement for example
echo "$variable";

**Comment by dcreager** [comment]
That should definitely be possible.  That kind of expression is usually called an "interpolation".  We parse those correctly in Python, for instance, using [these grammar rules](https://github.com/tree-sitter/tree-sitter-python/blob/3196e288650992bca2399dda15ac703c342a22bb/grammar.js#L867-L879). (In Python an interpolation is in braces, so your example would look like `"{variable}"` instead of `"$variable"`.)

**Comment by MurdeRMelodY** [comment]
So there's no way to highlight "$variable1|$variable2" for example?

**Comment by dcreager** [comment]
Not right now.  Someone would have to add additional rules to the PHP grammar to parse variable references inside of a string.

**Comment by MurdeRMelodY** [comment]
Ok, thanks.

**Comment by cfroystad** [comment]
FYI @MurdeRMelodY, tree-sitter-php now correctly parses strings in master and this should now be doable
