### ISSUE TITLE
qualified_name refers to both qualified and unqualified name in the grammar

### ISSUE THREAD

**Issue by cfroystad** [tree-sitter/tree-sitter-php#77]
Type: Bug/Unexpected behaviour

According to the [PHP specification](https://github.com/php/php-langspec/blob/8a7e96736ac18cdd159b7af2e7d1e4c666c9c822/spec/09-lexical-structure.md#grammar-qualified-name), a qualified_name can be both qualified and unqualified since the namespace is optional.

This leads us to use the node qualified_name to mean both qualified and unqualified name.

TODO: Investigate how other parsers solve this and propose a logical alternative (if one can be found)

**Comment by maxbrunsfeld** [comment]
Yeah, I'd be ok with diverging from the spec there, and having `qualified_name` always begin with a namespace. If we did that, then everywhere that we *use* `$.qualfied_name`, we'd have to make sure to include `$.name` as an alternative.

I think this would probably be an improvement, because in the case of *unqualified* names, there would be less redundant "wrapper" nodes. And also `qualified_name` would have a more stable internal structure.
